def print_banner(self):
        print(r"""
   __    _       _   __  __ _           _ 
  / /   (_)     | | |  \/  (_)         | |
 / /    _ _ __ | | | \  / |_ _ __   __| |
/ /    | | '_ \| | | |\/| | | '_ \ / _` |
\ \    | | | | | | | |  | | | | | | (_| |
 \_\   |_|_| |_|_| |_|  |_|_|_| |_|\__,_|
      SOVEREIGN ENGINE | V1.0 | HUAWEI NCE
        """)
        print(f"[*] Target File: {self.input_file}")
        print(f"[*] Timestamp:   {self.timestamp}")
        print("-" * 50)

import pandas as pd
from datetime import datetime

class LinkMindSovereign:
    """
    Decision Master: Generates Execution (Action) and Rollback commands 
    to ensure IF Board capacity is released with absolute safety.
    """
    def __init__(self, input_excel):
        self.input_file = input_excel
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        self.action_file = f"EXECUTE_PLAN_{self.timestamp}.mml"
        self.rollback_file = f"ROLLBACK_PLAN_{self.timestamp}.mml"
        self.total_bw_freed = 0

    def load_and_validate(self):
        try:
            self.df = pd.read_excel(self.input_file)
            # Critical columns required for Rollback logic
            required_cols = ['Service ID', 'Source NE', 'Source Slot', 'Source Port', 
                             'Sink NE', 'Sink Slot', 'Sink Port', 
                             'Current_E1_Capacity', 'Wasted_E1s']
            
            missing = [c for c in required_cols if c not in self.df.columns]
            if missing:
                print(f"❌ Error: The following columns are missing in the Excel file (Required for Rollback): {missing}")
                return False
            return True
        except Exception as e:
            print(f"❌ File Error: {e}")
            return False

    def generate_scripts(self):
        if not self.load_and_validate(): return

        with open(self.action_file, 'w') as f_act, open(self.rollback_file, 'w') as f_roll:
            
            # --- Writing Headers ---
            header = f"// GENERATED BY LINKMIND SOVEREIGN | {self.timestamp}\n"
            f_act.write(header + "// 🚨 MODE: DESTRUCTION (EXECUTE WITH CAUTION)\n\n")
            f_roll.write(header + "// 🛡️ MODE: SALVAGE (ROLLBACK/EMERGENCY)\n\n")

            for index, row in self.df.iterrows():
                # Extract Data
                srv_id = row['Service ID']
                ne_name = row['Source NE'] # Focusing commands on Source as an example
                slot = row['Source Slot']
                port = row['Source Port']
                old_cap = int(row['Current_E1_Capacity'])
                wasted = int(row['Wasted_E1s'])
                
                # Calculate New Capacity (after release)
                new_cap = max(0, old_cap - wasted)
                
                # Skip if there is no waste to process
                if wasted <= 0: continue

                # ==========================================
                # 1. EXECUTION COMMANDS (ACTION FILE)
                # ==========================================
                f_act.write(f"// --- SITE: {ne_name} | LINK: {slot}/{port} ---\n")
                
                # A. Delete Logical Service
                f_act.write(f"// Step 1: Deactivate & Delete Service {srv_id}\n")
                f_act.write(f"DEA-SDH-TRAIL: ID={srv_id};\n") # Or Deactivate Cross-Connect
                f_act.write(f"DEL-SDH-TRAIL: ID={srv_id};\n")
                
                # B. Release Hardware (IF Board Capacity) - The Core Feature 💎
                f_act.write(f"// Step 2: Shrink IF Capacity from {old_cap} to {new_cap} E1s\n")
                # This command tells the board: don't reserve 16 E1s, only reserve 10, convert the rest to Ethernet.
                f_act.write(f"CFG-IFPORT-HYBRID: BID={slot}, PID={port}, E1CAPACITY={new_cap};\n")
                f_act.write("\n")

                # ==========================================
                # 2. ROLLBACK COMMANDS (ROLLBACK FILE)
                # ==========================================
                f_roll.write(f"// --- REVERTING SITE: {ne_name} ---\n")
                
                # A. Restore Hardware Capacity First (Expand the pipe before pumping traffic)
                f_roll.write(f"// Step 1: Restore IF Capacity back to {old_cap}\n")
                f_roll.write(f"CFG-IFPORT-HYBRID: BID={slot}, PID={port}, E1CAPACITY={old_cap};\n")
                
                # B. Re-create the Service
                # Note: Accurate creation requires details like Timeslots, which should be in the Excel.
                # Here we write a generic command for illustration.
                f_roll.write(f"// Step 2: Re-Create Service {srv_id}\n")
                f_roll.write(f"ADD-SDH-TRAIL: ID={srv_id}, SRC-NE={ne_name}, SRC-BOARD={slot}, SRC-PORT={port}, ...;\n")
                f_roll.write("\n")

                self.total_bw_freed += (wasted * 2.048)

            # --- Conclusion ---
            summary = f"// TOTAL BANDWIDTH FREED: {self.total_bw_freed:.2f} Mbps\n"
            f_act.write(summary)
            print(f"✅ Finished successfully!")
            print(f"📂 Action File: {self.action_file}")
            print(f"🛡️ Rollback File: {self.rollback_file}")

# --- Execution ---
if __name__ == "__main__":
    # Ensure your Excel file contains the required columns
    bot = LinkMindSovereign("Final_Action_Plan.xlsx")
    bot.generate_scripts()